
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-i-xenial
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-i
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: arlon/cluster-i/workload/xenial
    targetRevision: HEAD
