
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-g-cluster-g-guestbook
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-g
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: cluster-g/workload/cluster-g-guestbook
    targetRevision: HEAD
