apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/bcle/fleet-infra.git//baseclusters/mykubeadm?ref=main
configurations:
- configurations.yaml
patches:
- target:
    group: infrastructure.cluster.x-k8s.io
    version: v1beta1
    kind: AWSCluster
  path: patch.yaml
