apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kubernetes.io/metadata.name":"default"},"name":"default"},"spec":{"finalizers":["kubernetes"]}}
  labels:
    kubernetes.io/metadata.name: default
  name: default
spec:
  finalizers:
  - kubernetes
