
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-a-profile-dyntest-1
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-a
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: profiles/dyntest-1
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: cluster-a
