
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-x-guestbook-ref
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-x
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: bundles/guestbook-ref
    targetRevision: HEAD
