
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-b-guestbook
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-b
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: arlon/cluster-b/workload/guestbook
    targetRevision: HEAD
