
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-b-profile-dyntest-1
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: profiles/dyntest-1/mgmt
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: cluster-b
