apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    arlon-type: placeholder
    managed-by: arlon
  name: placeholder-{{ .Values.profileAppName }}
  namespace: arlon
data:
  profileName: {{ .Values.profileAppName }}