---
# Source: arlon-cluster/templates/ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-b
---
# Source: arlon-cluster/templates/cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: cluster-b-md-0
  namespace: cluster-b
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: leb
---
# Source: arlon-cluster/templates/cluster.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: cluster-b-control-plane
  namespace: cluster-b
spec:
  region: us-west-2
  sshKeyName: leb
  version: v1.18.16
---
# Source: arlon-cluster/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-b
  namespace: cluster-b
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: cluster-b-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: cluster-b-control-plane
---
# Source: arlon-cluster/templates/clusterregistration.yaml
apiVersion: arlon.io/v1
kind: ClusterRegistration
metadata:
  name: cluster-b
  namespace: cluster-b
spec:
  clusterName: cluster-b
  kubeconfigSecretName: cluster-b-kubeconfig
  kubeconfigSecretKeyName: value
---
# Source: arlon-cluster/templates/cluster.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: cluster-b-md-0
  namespace: cluster-b
spec:
  template: {}
---
# Source: arlon-cluster/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: cluster-b-md-0
  namespace: cluster-b
spec:
  clusterName: cluster-b
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: cluster-b-md-0
      clusterName: cluster-b
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: cluster-b-md-0
      version: v1.18.16
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-b-guestbook-ref
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-b
    namespace: default
  project: default
  source:
    repoURL: https://github.com/bcle/fleet-infra.git
    path: bundles/guestbook-ref
    targetRevision: HEAD

